### ISSUE TITLE
Chromium can't run without qt5-wayland 

### ISSUE THREAD

**Issue by ffs-akl** [stefonarch/LXQt-Wayland-files#6] opened 2024-05-28 07:06 UTC
Normally, Chromium can run on qt6-wayland only, qt5-wayland is not required. But I don't know why, in LXQT2.0+Kwin_wayland with qt6-wayland, I have to install qt5-wayland for chromium to work.

Edited:
it is no problem to run chromium in Plasma6 with qt6-wayland only

**Comment by stefonarch** [comment] 2024-05-28 11:15
No idea about that. I removed temporarily qt5-wayland (needed by copyq) and chromium starts (I don't use it regularly). What error do you get, if any, from cli?

**Comment by ffs-akl** [comment] 2024-05-28 12:36
Here is the output from cli:
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.
[0528/203316.484265:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0528/203316.516310:ERROR:file_io_posix.cc(145)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory (2)
[0528/203316.516380:ERROR:file_io_posix.cc(145)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: No such file or directory (2)

after installed qt5-wayland, everything is ok.

**Comment by stefonarch** [comment] 2024-05-28 14:05
```
$ chromium
[252502:252502:0528/155409.349517:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[252502:252502:0528/155412.028705:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[252502:252502:0528/155412.036121:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
```
and opens fine. But it's running in xwayland I see.

**Comment by ffs-akl** [comment] 2024-05-28 16:00
It should be an issue of  lxqt-wayland, There is no concern with kwin_wayland.
I've tried lxqt-labwc and  there is  the same issue with chromium

**Comment by stefonarch** [comment] 2024-05-28 17:57
It could be about the env vars that are set at startup. As I said I don't use chromium, and didn't investigate yet why it starts in xwayland mode here and what is needed to use for it to use xdg-shell.

**Comment by stefonarch** [comment] 2024-05-28 18:27
Ok, I set the flag needed `--ozone-platform-hint=auto` to enable wayland mode and now I can reproduce it. 

But also both `labwc -S chromium` and `kwin_wayland chromium` fail from tty, so it looks like this package is simply needed, as it [provides](https://archlinux.org/packages/extra/x86_64/qt5-wayland/files/) the plugin needed. I will check a plasma session later.

**Comment by stefonarch** [comment] 2024-05-28 19:28
I checked in plasma6 and it's how you describe. Conclusion: if you're not on plasma and want to use chromium in wayland mode you need `qt5-wayland`.

**Comment by ffs-akl** [comment] 2024-05-28 23:30
Thank  you！ 
It seems that plasma has done a lot of work, is there any chance of porting what plasma does to LXQT sessions?

**Comment by stefonarch** [comment] 2024-05-29 05:36
Plasma and kwin have sure much features (some people may say "bloat"),  but on the other side this can port  also to many bugs. We don't want to overcomplicate things. 
If you have a feature in mind you'd like to see you can still make a feature request.

**Closed as completed by stefonarch** 2024-05-29 05:36 UTC

**Comment by ffs-akl** [comment] 2024-05-31 02:27
> Plasma and kwin have sure much features (some people may say "bloat"), but on the other side this can port also to many bugs. We don't want to overcomplicate things. If you have a feature in mind you'd like to see you can still make a feature request.

In lxqt-labwc,I've found that Chromium can run on qt6-wayland without qt5-base installed. So, It probably really is an issue with environment variable
Edited:
chromium run on wayland without qt5-base installed ,not on xwayland
